name: build_and_publish_image
on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:

jobs:
  publish-source-stackadapt-image:
    runs-on: ubuntu-latest
    environment:
      prod
    steps:
    - uses: actions/checkout@v3

    - name: Docker Metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: |
          ghcr.io/community-tech-alliance/source-stackadapt
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=sha

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      run: |
        echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u communitytechalliance --password-stdin
      
    - name: Build and tag image
      run: |
        COMMIT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
        docker build . -t communitytechalliance/${{ github.repository }}:$COMMIT_SHA

    - name: Push image to Docker Hub
      run: docker push communitytechalliance/${{ github.repository }}:$COMMIT_SHA

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}